name: CI with Reusable Python Workflow

on:
  push:
    branches:
      - main
      - Init
  pull_request:
    branches:
      - main

jobs:
  ci:
    uses: mi-parkes/custom-reusable-workflow/.github/workflows/ci-python.yml@main
    with:
      python-version: '3.10'
      coverage: false
